name: Wallet
options:
  bundleIdPrefix: com.kevinthau
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"

settings:
  base:
    SWIFT_VERSION: "5.9"
    GENERATE_INFOPLIST_FILE: NO

targets:
  Wallet:
    type: application
    platform: iOS
    sources:
      - Wallet
    settings:
      base:
        INFOPLIST_FILE: Wallet/Info.plist
        CODE_SIGN_ENTITLEMENTS: Wallet/Wallet.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: com.kevinthau.wallet
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        DEVELOPMENT_TEAM: "3JXY2MS2Y3"
    entitlements:
      path: Wallet/Wallet.entitlements
